# This workflow deploys a storage account to Azure

name: DeployToAzure

# Controls where the Workflow will run
on:
  push:
    branches: 
    - master

  workflow_dispatch: 

jobs:
  deploytostaging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Azure Login
      
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZ_CREDENTIALS }}
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
          enable-AzPSSession: true         

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1.2.0
        with:
          # Specify the Az PowerShell script here.
          inlineScript: New-AzResourceGroup -Name GitHubExempleRG -location EastUS -Force
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.9
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: GitHubExempleRG
          # Specify the path or URL to the Azure Resource Manager template.
          template: main.bicep
         

